{
    "openapi": "3.0.1",
    "info": {
        "title": "CREA AA Italian historical weather series",
        "description": "A large collection of historical weather data curated by CREA-AA.",
        "version": "1.0"
    },
    "servers": [
        {
            "url": "https://api.anaee.eu/crea-aa-dailymeteo"
        }
    ],
    "paths": {
        "/getRasterData": {
            "post": {
                "tags": [
                    "wheater",
                    "Italy",
                    "raster",
                    "data"
                ],
                "summary": "getRasterData",
                "description": "This API allows programmatic access to an extensive collection of historical weather series covering the whole Italian territory with 10 km resolution, starting from 1961.\nIt allows to retrieve data contained within a time interval of interest and/or a geographical area of interest.",
                "operationId": "post-getrasterdata",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/getStations_CREA"
                            },
                            "example": {
                                "startTime": "2016-09-16T12:00:00.0000000+00:00",
                                "endTime": "2016-09-18T12:00:00.0000000+00:00",
                                "wkt": "POLYGON((10.90409785221798 44.30484478153003,10.66239863346798 44.42265911183206,10.66789179753048 44.66148418831872,10.85465937565548 44.72786742900223,11.05790644596798 44.78247884124713,11.04142695378048 45.314166848104314,10.96452265690548 45.356642784492756,10.98100214909298 45.572389969686256,11.45890742253048 45.65308230226008,11.45890742253048 45.31802961340594,11.36552363346798 45.27939011142026,11.38749628971798 44.798072622487574,11.78300410221798 44.65757692202672,11.76103144596798 44.245848768884706,11.38200312565548 44.23404245893648,11.23918086003048 44.35592674819006,11.09635859440548 44.28518602502541,10.90409785221798 44.30484478153003))",
                                "mode": "json"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "null"
                    }
                }
            }
        },
        "/getNearestRasterData": {
            "post": {
                "tags": [
                    "wheater",
                    "Italy",
                    "raster",
                    "data"
                ],
                "summary": "getNearestRasterData",
                "description": "This API allows programmatic access to an extensive collection of historical weather series covering the whole Italian territory with 10 km resolution, starting from 1961.\nIt allows to retrieve data from the nearest known locations to a given geographical area of interest.",
                "operationId": "post-getnearestrasterdata",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/getNearestStations_CREA"
                            },
                            "example": {
                                "startTime": "2016-09-16T12:00:00.0000000+00:00",
                                "endTime": "2016-09-18T12:00:00.0000000+00:00",
                                "wkt": "POINT(10.904 44.304)",
                                "limit": "3",
                                "mode": "csv"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "null"
                    }
                }
            }
        },
        "/getNearestStationData": {
            "post": {
                "summary": "getNearestStationData",
                "description": "his API allows programmatic access to weather station data from a vast number of different sources our engineers took the hassle of integrating with each other.\nCREA does not gurantee this data to be complete, nor correct, nor on time.\nIt allows to retrieve data from the nearest known locations to a given geographical area of interest.",
                "operationId": "post-getneareststationdata",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/getNearestStations_CREA"
                            },
                            "example": {
                                "startTime": "2019-09-16T12:00:00.0000000+00:00",
                                "endTime": "2019-09-22T12:00:00.0000000+00:00",
                                "wkt": "POINT(10.904 44.304)",
                                "limit": "5",
                                "mode": "csv"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "null"
                    }
                }
            }
        },
        "/getStationData": {
            "post": {
                "tags": [
                    "wheater",
                    "Italy",
                    "data",
                    "stations"
                ],
                "summary": "getStationData",
                "description": "This API allows programmatic access to weather station data from a vast number of different sources our engineers took the hassle of integrating with each other. CREA does not guarantee this data to be complete, nor correct, nor on time. It allows to retrieve data contained within a time interval of interest and/or a geographical area of interest.",
                "operationId": "post-getstationdata",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/getStations_CREA"
                            },
                            "example": {
                                "startTime": "2021-09-01T06:30:00.0000000+00:00",
                                "endTime": "2021-09-01T02:30:00.0000000+00:00",
                                "timestep": "hour",
                                "wkt": "POLYGON((9.78275171422652 44.61867418489613,9.49710718297652 44.69682189529362,9.29935327672652 44.58738561072099,9.18948999547652 44.45422117923017,9.21146265172652 44.26570621251402,9.31033960485152 44.179100819964994,9.50809351110152 44.17122128508731,9.72782007360152 44.17122128508731,9.72782007360152 44.06869152453934,9.74979272985152 43.997605159760816,9.90360132360152 43.918520308039206,10.12332788610152 43.918520308039206,10.38699976110152 43.96598385036578,10.47489038610152 44.10814710381382,10.47489038610152 44.234228083330734,10.43094507360152 44.36003951455455,10.40897241735152 44.45422117923017,10.52982202672652 44.56390812156246,10.67264429235152 44.689011863789595,10.81546655797652 44.82163915658955,10.94730249547652 45.07822317676609,10.93631616735152 45.34910432956281,10.80448022985152 45.5110137202116,10.56278101110152 45.557188240435885,10.33206812047652 45.48791224286834,10.17825952672652 45.24090669871777,10.17825952672652 45.13250262841761,10.17825952672652 44.992822619143865,10.12332788610152 44.7436599661329,10.04642358922652 44.657761205416016,9.91458765172652 44.60303200420828,9.78275171422652 44.61867418489613))",
                                "mode": "json"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "null"
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "getStations_CREA": {
                "required": [
                    "startTime"
                ],
                "type": "object",
                "properties": {
                    "startTime": {
                        "type": "string",
                        "description": "start time of the interval of interest"
                    },
                    "endTime": {
                        "type": "string",
                        "description": "end time of the interval of interest "
                    },
                    "country": {
                        "type": "string",
                        "description": "A country identifier to limit to the spatial search"
                    },
                    "group": {
                        "type": "string",
                        "description": "A group of stations to limit to the scope of the spatial search"
                    },
                    "stations": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "An array of station identifiers to limit to the scope of the spatial search"
                    },
                    "wkt": {
                        "type": "string",
                        "description": "Area of interest expressed in WKT format"
                    },
                    "timezone": {
                        "type": "string",
                        "description": "The timezone to which startTime and endTime refer to."
                    },
                    "timeStep": {
                        "enum": [
                            "day",
                            "hour"
                        ],
                        "type": "string",
                        "description": "The timestep you'd like your timeseries to have."
                    },
                    "mode": {
                        "enum": [
                            "CSV",
                            "csv",
                            "Csv",
                            "Comma Separated Values",
                            "comma separated values",
                            "JSON",
                            "json",
                            "Json",
                            "JavaScript Object Notation",
                            "javascript object notation",
                            "JSONCSV",
                            "JSON-CSV",
                            "jsoncsv",
                            "json-csv",
                            "Json-Csv",
                            "jsonCsv",
                            "JsonCsv"
                        ],
                        "type": "string",
                        "description": "the desired output format."
                    }
                }
            },
            "getNearestStations_CREA": {
                "required": [
                    "startTime",
                    "wkt"
                ],
                "type": "object",
                "properties": {
                    "startTime": {
                        "type": "string",
                        "description": "start time of the interval of interest"
                    },
                    "endTime": {
                        "type": "string",
                        "description": "end time of the interval of interest "
                    },
                    "limit": {
                        "type": "string",
                        "description": "how many stations/points to consider"
                    },
                    "country": {
                        "type": "string",
                        "description": "A country identifier to limit to the spatial search"
                    },
                    "group": {
                        "type": "string",
                        "description": "A group of stations to limit to the scope of the spatial search"
                    },
                    "stations": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "An array of station identifiers to limit to the scope of the spatial search"
                    },
                    "wkt": {
                        "type": "string",
                        "description": "Area of interest expressed in WKT format"
                    },
                    "timezone": {
                        "type": "string",
                        "description": "The timezone to which startTime and endTime refer to."
                    },
                    "timeStep": {
                        "enum": [
                            "day",
                            "hour"
                        ],
                        "type": "string",
                        "description": "The timestep you'd like your timeseries to have."
                    },
                    "mode": {
                        "enum": [
                            "CSV",
                            "csv",
                            "Csv",
                            "Comma Separated Values",
                            "comma separated values",
                            "JSON",
                            "json",
                            "Json",
                            "JavaScript Object Notation",
                            "javascript object notation",
                            "JSONCSV",
                            "JSON-CSV",
                            "jsoncsv",
                            "json-csv",
                            "Json-Csv",
                            "jsonCsv",
                            "JsonCsv"
                        ],
                        "type": "string",
                        "description": "the desired output format."
                    }
                }
            }
        },
        "securitySchemes": {
            "apiKeyHeader": {
                "type": "apiKey",
                "name": "Ocp-Apim-Subscription-Key",
                "in": "header"
            },
            "apiKeyQuery": {
                "type": "apiKey",
                "name": "subscription-key",
                "in": "query"
            }
        }
    },
    "security": [
        {
            "apiKeyHeader": []
        },
        {
            "apiKeyQuery": []
        }
    ]
}